#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import pprint
import sys

"""
Either use the CODES variable from this file to get the table.
If you want to update the list of codes, update the ISO-639-2_utf-8.txt file,
Remove the generated code at the end of the file (big part), and run:
./iso639.py ISO-639-2_utf-8.txt,
put the output at the end at the file.
"""

def main():
    """
    Read the file given by http://www.loc.gov/standards/iso639-2/
    Returns the list of codes in a table of dict.
    """
    parser = argparse.ArgumentParser(
        description="Generate dictionary of ISO639 codes")
    parser.add_argument('iso639_file')
    args = parser.parse_args()

    codes = []

    with open(args.iso639_file) as f:
        for line in f:
            parts = line.split('|')
            try:
                code = {}

                code['3L'] = parts[0].strip()
                code['2L'] = parts[2].strip()
                code['english'] = parts[3].strip()
                code['french'] = parts[4].strip()
            except IndexError:
                pass
            else:
                codes.append(code)

    print "CODES = \\"
    pprint.pprint(codes, width=78)

if __name__ == '__main__':
    sys.exit(main())

## Generated part goes here:
CODES = \
[{'2L': 'aa', '3L': '\xef\xbb\xbfaar', 'english': 'Afar', 'french': 'afar'},
 {'2L': 'ab', '3L': 'abk', 'english': 'Abkhazian', 'french': 'abkhaze'},
 {'2L': '', '3L': 'ace', 'english': 'Achinese', 'french': 'aceh'},
 {'2L': '', '3L': 'ach', 'english': 'Acoli', 'french': 'acoli'},
 {'2L': '', '3L': 'ada', 'english': 'Adangme', 'french': 'adangme'},
 {'2L': '',
  '3L': 'ady',
  'english': 'Adyghe; Adygei',
  'french': 'adygh\xc3\xa9'},
 {'2L': '',
  '3L': 'afa',
  'english': 'Afro-Asiatic languages',
  'french': 'afro-asiatiques, langues'},
 {'2L': '', '3L': 'afh', 'english': 'Afrihili', 'french': 'afrihili'},
 {'2L': 'af', '3L': 'afr', 'english': 'Afrikaans', 'french': 'afrikaans'},
 {'2L': '', '3L': 'ain', 'english': 'Ainu', 'french': 'a\xc3\xafnou'},
 {'2L': 'ak', '3L': 'aka', 'english': 'Akan', 'french': 'akan'},
 {'2L': '', '3L': 'akk', 'english': 'Akkadian', 'french': 'akkadien'},
 {'2L': 'sq', '3L': 'alb', 'english': 'Albanian', 'french': 'albanais'},
 {'2L': '', '3L': 'ale', 'english': 'Aleut', 'french': 'al\xc3\xa9oute'},
 {'2L': '',
  '3L': 'alg',
  'english': 'Algonquian languages',
  'french': 'algonquines, langues'},
 {'2L': '',
  '3L': 'alt',
  'english': 'Southern Altai',
  'french': 'altai du Sud'},
 {'2L': 'am', '3L': 'amh', 'english': 'Amharic', 'french': 'amharique'},
 {'2L': '',
  '3L': 'ang',
  'english': 'English, Old (ca.450-1100)',
  'french': 'anglo-saxon (ca.450-1100)'},
 {'2L': '', '3L': 'anp', 'english': 'Angika', 'french': 'angika'},
 {'2L': '',
  '3L': 'apa',
  'english': 'Apache languages',
  'french': 'apaches, langues'},
 {'2L': 'ar', '3L': 'ara', 'english': 'Arabic', 'french': 'arabe'},
 {'2L': '',
  '3L': 'arc',
  'english': 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)',
  'french': "aram\xc3\xa9en d'empire (700-300 BCE)"},
 {'2L': 'an', '3L': 'arg', 'english': 'Aragonese', 'french': 'aragonais'},
 {'2L': 'hy',
  '3L': 'arm',
  'english': 'Armenian',
  'french': 'arm\xc3\xa9nien'},
 {'2L': '',
  '3L': 'arn',
  'english': 'Mapudungun; Mapuche',
  'french': 'mapudungun; mapuche; mapuce'},
 {'2L': '', '3L': 'arp', 'english': 'Arapaho', 'french': 'arapaho'},
 {'2L': '',
  '3L': 'art',
  'english': 'Artificial languages',
  'french': 'artificielles, langues'},
 {'2L': '', '3L': 'arw', 'english': 'Arawak', 'french': 'arawak'},
 {'2L': 'as', '3L': 'asm', 'english': 'Assamese', 'french': 'assamais'},
 {'2L': '',
  '3L': 'ast',
  'english': 'Asturian; Bable; Leonese; Asturleonese',
  'french': 'asturien; bable; l\xc3\xa9onais; asturol\xc3\xa9onais'},
 {'2L': '',
  '3L': 'ath',
  'english': 'Athapascan languages',
  'french': 'athapascanes, langues'},
 {'2L': '',
  '3L': 'aus',
  'english': 'Australian languages',
  'french': 'australiennes, langues'},
 {'2L': 'av', '3L': 'ava', 'english': 'Avaric', 'french': 'avar'},
 {'2L': 'ae', '3L': 'ave', 'english': 'Avestan', 'french': 'avestique'},
 {'2L': '', '3L': 'awa', 'english': 'Awadhi', 'french': 'awadhi'},
 {'2L': 'ay', '3L': 'aym', 'english': 'Aymara', 'french': 'aymara'},
 {'2L': 'az',
  '3L': 'aze',
  'english': 'Azerbaijani',
  'french': 'az\xc3\xa9ri'},
 {'2L': '',
  '3L': 'bad',
  'english': 'Banda languages',
  'french': 'banda, langues'},
 {'2L': '',
  '3L': 'bai',
  'english': 'Bamileke languages',
  'french': 'bamil\xc3\xa9k\xc3\xa9, langues'},
 {'2L': 'ba', '3L': 'bak', 'english': 'Bashkir', 'french': 'bachkir'},
 {'2L': '', '3L': 'bal', 'english': 'Baluchi', 'french': 'baloutchi'},
 {'2L': 'bm', '3L': 'bam', 'english': 'Bambara', 'french': 'bambara'},
 {'2L': '', '3L': 'ban', 'english': 'Balinese', 'french': 'balinais'},
 {'2L': 'eu', '3L': 'baq', 'english': 'Basque', 'french': 'basque'},
 {'2L': '', '3L': 'bas', 'english': 'Basa', 'french': 'basa'},
 {'2L': '',
  '3L': 'bat',
  'english': 'Baltic languages',
  'french': 'baltes, langues'},
 {'2L': '', '3L': 'bej', 'english': 'Beja; Bedawiyet', 'french': 'bedja'},
 {'2L': 'be',
  '3L': 'bel',
  'english': 'Belarusian',
  'french': 'bi\xc3\xa9lorusse'},
 {'2L': '', '3L': 'bem', 'english': 'Bemba', 'french': 'bemba'},
 {'2L': 'bn', '3L': 'ben', 'english': 'Bengali', 'french': 'bengali'},
 {'2L': '',
  '3L': 'ber',
  'english': 'Berber languages',
  'french': 'berb\xc3\xa8res, langues'},
 {'2L': '', '3L': 'bho', 'english': 'Bhojpuri', 'french': 'bhojpuri'},
 {'2L': 'bh',
  '3L': 'bih',
  'english': 'Bihari languages',
  'french': 'langues biharis'},
 {'2L': '', '3L': 'bik', 'english': 'Bikol', 'french': 'bikol'},
 {'2L': '', '3L': 'bin', 'english': 'Bini; Edo', 'french': 'bini; edo'},
 {'2L': 'bi', '3L': 'bis', 'english': 'Bislama', 'french': 'bichlamar'},
 {'2L': '', '3L': 'bla', 'english': 'Siksika', 'french': 'blackfoot'},
 {'2L': '',
  '3L': 'bnt',
  'english': 'Bantu (Other)',
  'french': 'bantoues, autres langues'},
 {'2L': 'bs', '3L': 'bos', 'english': 'Bosnian', 'french': 'bosniaque'},
 {'2L': '', '3L': 'bra', 'english': 'Braj', 'french': 'braj'},
 {'2L': 'br', '3L': 'bre', 'english': 'Breton', 'french': 'breton'},
 {'2L': '',
  '3L': 'btk',
  'english': 'Batak languages',
  'french': 'batak, langues'},
 {'2L': '', '3L': 'bua', 'english': 'Buriat', 'french': 'bouriate'},
 {'2L': '', '3L': 'bug', 'english': 'Buginese', 'french': 'bugi'},
 {'2L': 'bg', '3L': 'bul', 'english': 'Bulgarian', 'french': 'bulgare'},
 {'2L': 'my', '3L': 'bur', 'english': 'Burmese', 'french': 'birman'},
 {'2L': '', '3L': 'byn', 'english': 'Blin; Bilin', 'french': 'blin; bilen'},
 {'2L': '', '3L': 'cad', 'english': 'Caddo', 'french': 'caddo'},
 {'2L': '',
  '3L': 'cai',
  'english': 'Central American Indian languages',
  'french': "am\xc3\xa9rindiennes de L'Am\xc3\xa9rique centrale, langues"},
 {'2L': '',
  '3L': 'car',
  'english': 'Galibi Carib',
  'french': 'karib; galibi; carib'},
 {'2L': 'ca',
  '3L': 'cat',
  'english': 'Catalan; Valencian',
  'french': 'catalan; valencien'},
 {'2L': '',
  '3L': 'cau',
  'english': 'Caucasian languages',
  'french': 'caucasiennes, langues'},
 {'2L': '', '3L': 'ceb', 'english': 'Cebuano', 'french': 'cebuano'},
 {'2L': '',
  '3L': 'cel',
  'english': 'Celtic languages',
  'french': 'celtiques, langues; celtes, langues'},
 {'2L': 'ch', '3L': 'cha', 'english': 'Chamorro', 'french': 'chamorro'},
 {'2L': '', '3L': 'chb', 'english': 'Chibcha', 'french': 'chibcha'},
 {'2L': 'ce',
  '3L': 'che',
  'english': 'Chechen',
  'french': 'tch\xc3\xa9tch\xc3\xa8ne'},
 {'2L': '',
  '3L': 'chg',
  'english': 'Chagatai',
  'french': 'djaghata\xc3\xaf'},
 {'2L': 'zh', '3L': 'chi', 'english': 'Chinese', 'french': 'chinois'},
 {'2L': '', '3L': 'chk', 'english': 'Chuukese', 'french': 'chuuk'},
 {'2L': '', '3L': 'chm', 'english': 'Mari', 'french': 'mari'},
 {'2L': '',
  '3L': 'chn',
  'english': 'Chinook jargon',
  'french': 'chinook, jargon'},
 {'2L': '', '3L': 'cho', 'english': 'Choctaw', 'french': 'choctaw'},
 {'2L': '',
  '3L': 'chp',
  'english': 'Chipewyan; Dene Suline',
  'french': 'chipewyan'},
 {'2L': '', '3L': 'chr', 'english': 'Cherokee', 'french': 'cherokee'},
 {'2L': 'cu',
  '3L': 'chu',
  'english': 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic',
  'french': "slavon d'\xc3\xa9glise; vieux slave; slavon liturgique; vieux bulgare"},
 {'2L': 'cv', '3L': 'chv', 'english': 'Chuvash', 'french': 'tchouvache'},
 {'2L': '', '3L': 'chy', 'english': 'Cheyenne', 'french': 'cheyenne'},
 {'2L': '',
  '3L': 'cmc',
  'english': 'Chamic languages',
  'french': 'chames, langues'},
 {'2L': '', '3L': 'cop', 'english': 'Coptic', 'french': 'copte'},
 {'2L': 'kw', '3L': 'cor', 'english': 'Cornish', 'french': 'cornique'},
 {'2L': 'co', '3L': 'cos', 'english': 'Corsican', 'french': 'corse'},
 {'2L': '',
  '3L': 'cpe',
  'english': 'Creoles and pidgins, English based',
  'french': "cr\xc3\xa9oles et pidgins bas\xc3\xa9s sur l'anglais"},
 {'2L': '',
  '3L': 'cpf',
  'english': 'Creoles and pidgins, French-based',
  'french': 'cr\xc3\xa9oles et pidgins bas\xc3\xa9s sur le fran\xc3\xa7ais'},
 {'2L': '',
  '3L': 'cpp',
  'english': 'Creoles and pidgins, Portuguese-based',
  'french': 'cr\xc3\xa9oles et pidgins bas\xc3\xa9s sur le portugais'},
 {'2L': 'cr', '3L': 'cre', 'english': 'Cree', 'french': 'cree'},
 {'2L': '',
  '3L': 'crh',
  'english': 'Crimean Tatar; Crimean Turkish',
  'french': 'tatar de Crim\xc3\xa9'},
 {'2L': '',
  '3L': 'crp',
  'english': 'Creoles and pidgins',
  'french': 'cr\xc3\xa9oles et pidgins'},
 {'2L': '', '3L': 'csb', 'english': 'Kashubian', 'french': 'kachoube'},
 {'2L': '',
  '3L': 'cus',
  'english': 'Cushitic languages',
  'french': 'couchitiques, langues'},
 {'2L': 'cs', '3L': 'cze', 'english': 'Czech', 'french': 'tch\xc3\xa8que'},
 {'2L': '', '3L': 'dak', 'english': 'Dakota', 'french': 'dakota'},
 {'2L': 'da', '3L': 'dan', 'english': 'Danish', 'french': 'danois'},
 {'2L': '', '3L': 'dar', 'english': 'Dargwa', 'french': 'dargwa'},
 {'2L': '',
  '3L': 'day',
  'english': 'Land Dayak languages',
  'french': 'dayak, langues'},
 {'2L': '', '3L': 'del', 'english': 'Delaware', 'french': 'delaware'},
 {'2L': '',
  '3L': 'den',
  'english': 'Slave (Athapascan)',
  'french': 'esclave (athapascan)'},
 {'2L': '', '3L': 'dgr', 'english': 'Dogrib', 'french': 'dogrib'},
 {'2L': '', '3L': 'din', 'english': 'Dinka', 'french': 'dinka'},
 {'2L': 'dv',
  '3L': 'div',
  'english': 'Divehi; Dhivehi; Maldivian',
  'french': 'maldivien'},
 {'2L': '', '3L': 'doi', 'english': 'Dogri', 'french': 'dogri'},
 {'2L': '',
  '3L': 'dra',
  'english': 'Dravidian languages',
  'french': 'dravidiennes, langues'},
 {'2L': '', '3L': 'dsb', 'english': 'Lower Sorbian', 'french': 'bas-sorabe'},
 {'2L': '', '3L': 'dua', 'english': 'Duala', 'french': 'douala'},
 {'2L': '',
  '3L': 'dum',
  'english': 'Dutch, Middle (ca.1050-1350)',
  'french': 'n\xc3\xa9erlandais moyen (ca. 1050-1350)'},
 {'2L': 'nl',
  '3L': 'dut',
  'english': 'Dutch; Flemish',
  'french': 'n\xc3\xa9erlandais; flamand'},
 {'2L': '', '3L': 'dyu', 'english': 'Dyula', 'french': 'dioula'},
 {'2L': 'dz', '3L': 'dzo', 'english': 'Dzongkha', 'french': 'dzongkha'},
 {'2L': '', '3L': 'efi', 'english': 'Efik', 'french': 'efik'},
 {'2L': '',
  '3L': 'egy',
  'english': 'Egyptian (Ancient)',
  'french': '\xc3\xa9gyptien'},
 {'2L': '', '3L': 'eka', 'english': 'Ekajuk', 'french': 'ekajuk'},
 {'2L': '', '3L': 'elx', 'english': 'Elamite', 'french': '\xc3\xa9lamite'},
 {'2L': 'en', '3L': 'eng', 'english': 'English', 'french': 'anglais'},
 {'2L': '',
  '3L': 'enm',
  'english': 'English, Middle (1100-1500)',
  'french': 'anglais moyen (1100-1500)'},
 {'2L': 'eo',
  '3L': 'epo',
  'english': 'Esperanto',
  'french': 'esp\xc3\xa9ranto'},
 {'2L': 'et', '3L': 'est', 'english': 'Estonian', 'french': 'estonien'},
 {'2L': 'ee', '3L': 'ewe', 'english': 'Ewe', 'french': '\xc3\xa9w\xc3\xa9'},
 {'2L': '', '3L': 'ewo', 'english': 'Ewondo', 'french': '\xc3\xa9wondo'},
 {'2L': '', '3L': 'fan', 'english': 'Fang', 'french': 'fang'},
 {'2L': 'fo',
  '3L': 'fao',
  'english': 'Faroese',
  'french': 'f\xc3\xa9ro\xc3\xafen'},
 {'2L': '', '3L': 'fat', 'english': 'Fanti', 'french': 'fanti'},
 {'2L': 'fj', '3L': 'fij', 'english': 'Fijian', 'french': 'fidjien'},
 {'2L': '',
  '3L': 'fil',
  'english': 'Filipino; Pilipino',
  'french': 'filipino; pilipino'},
 {'2L': 'fi', '3L': 'fin', 'english': 'Finnish', 'french': 'finnois'},
 {'2L': '',
  '3L': 'fiu',
  'english': 'Finno-Ugrian languages',
  'french': 'finno-ougriennes, langues'},
 {'2L': '', '3L': 'fon', 'english': 'Fon', 'french': 'fon'},
 {'2L': 'fr', '3L': 'fre', 'english': 'French', 'french': 'fran\xc3\xa7ais'},
 {'2L': '',
  '3L': 'frm',
  'english': 'French, Middle (ca.1400-1600)',
  'french': 'fran\xc3\xa7ais moyen (1400-1600)'},
 {'2L': '',
  '3L': 'fro',
  'english': 'French, Old (842-ca.1400)',
  'french': 'fran\xc3\xa7ais ancien (842-ca.1400)'},
 {'2L': '',
  '3L': 'frr',
  'english': 'Northern Frisian',
  'french': 'frison septentrional'},
 {'2L': '',
  '3L': 'frs',
  'english': 'Eastern Frisian',
  'french': 'frison oriental'},
 {'2L': 'fy',
  '3L': 'fry',
  'english': 'Western Frisian',
  'french': 'frison occidental'},
 {'2L': 'ff', '3L': 'ful', 'english': 'Fulah', 'french': 'peul'},
 {'2L': '', '3L': 'fur', 'english': 'Friulian', 'french': 'frioulan'},
 {'2L': '', '3L': 'gaa', 'english': 'Ga', 'french': 'ga'},
 {'2L': '', '3L': 'gay', 'english': 'Gayo', 'french': 'gayo'},
 {'2L': '', '3L': 'gba', 'english': 'Gbaya', 'french': 'gbaya'},
 {'2L': '',
  '3L': 'gem',
  'english': 'Germanic languages',
  'french': 'germaniques, langues'},
 {'2L': 'ka',
  '3L': 'geo',
  'english': 'Georgian',
  'french': 'g\xc3\xa9orgien'},
 {'2L': 'de', '3L': 'ger', 'english': 'German', 'french': 'allemand'},
 {'2L': '', '3L': 'gez', 'english': 'Geez', 'french': 'gu\xc3\xa8ze'},
 {'2L': '', '3L': 'gil', 'english': 'Gilbertese', 'french': 'kiribati'},
 {'2L': 'gd',
  '3L': 'gla',
  'english': 'Gaelic; Scottish Gaelic',
  'french': 'ga\xc3\xa9lique; ga\xc3\xa9lique \xc3\xa9cossais'},
 {'2L': 'ga', '3L': 'gle', 'english': 'Irish', 'french': 'irlandais'},
 {'2L': 'gl', '3L': 'glg', 'english': 'Galician', 'french': 'galicien'},
 {'2L': 'gv', '3L': 'glv', 'english': 'Manx', 'french': 'manx; mannois'},
 {'2L': '',
  '3L': 'gmh',
  'english': 'German, Middle High (ca.1050-1500)',
  'french': 'allemand, moyen haut (ca. 1050-1500)'},
 {'2L': '',
  '3L': 'goh',
  'english': 'German, Old High (ca.750-1050)',
  'french': 'allemand, vieux haut (ca. 750-1050)'},
 {'2L': '', '3L': 'gon', 'english': 'Gondi', 'french': 'gond'},
 {'2L': '', '3L': 'gor', 'english': 'Gorontalo', 'french': 'gorontalo'},
 {'2L': '', '3L': 'got', 'english': 'Gothic', 'french': 'gothique'},
 {'2L': '', '3L': 'grb', 'english': 'Grebo', 'french': 'grebo'},
 {'2L': '',
  '3L': 'grc',
  'english': 'Greek, Ancient (to 1453)',
  'french': "grec ancien (jusqu'\xc3\xa0 1453)"},
 {'2L': 'el',
  '3L': 'gre',
  'english': 'Greek, Modern (1453-)',
  'french': 'grec moderne (apr\xc3\xa8s 1453)'},
 {'2L': 'gn', '3L': 'grn', 'english': 'Guarani', 'french': 'guarani'},
 {'2L': '',
  '3L': 'gsw',
  'english': 'Swiss German; Alemannic; Alsatian',
  'french': 'suisse al\xc3\xa9manique; al\xc3\xa9manique; alsacien'},
 {'2L': 'gu', '3L': 'guj', 'english': 'Gujarati', 'french': 'goudjrati'},
 {'2L': '', '3L': 'gwi', 'english': "Gwich'in", 'french': "gwich'in"},
 {'2L': '', '3L': 'hai', 'english': 'Haida', 'french': 'haida'},
 {'2L': 'ht',
  '3L': 'hat',
  'english': 'Haitian; Haitian Creole',
  'french': 'ha\xc3\xaftien; cr\xc3\xa9ole ha\xc3\xaftien'},
 {'2L': 'ha', '3L': 'hau', 'english': 'Hausa', 'french': 'haoussa'},
 {'2L': '', '3L': 'haw', 'english': 'Hawaiian', 'french': 'hawa\xc3\xafen'},
 {'2L': 'he', '3L': 'heb', 'english': 'Hebrew', 'french': 'h\xc3\xa9breu'},
 {'2L': 'hz', '3L': 'her', 'english': 'Herero', 'french': 'herero'},
 {'2L': '', '3L': 'hil', 'english': 'Hiligaynon', 'french': 'hiligaynon'},
 {'2L': '',
  '3L': 'him',
  'english': 'Himachali languages; Western Pahari languages',
  'french': 'langues himachalis; langues paharis occidentales'},
 {'2L': 'hi', '3L': 'hin', 'english': 'Hindi', 'french': 'hindi'},
 {'2L': '', '3L': 'hit', 'english': 'Hittite', 'french': 'hittite'},
 {'2L': '', '3L': 'hmn', 'english': 'Hmong; Mong', 'french': 'hmong'},
 {'2L': 'ho', '3L': 'hmo', 'english': 'Hiri Motu', 'french': 'hiri motu'},
 {'2L': 'hr', '3L': 'hrv', 'english': 'Croatian', 'french': 'croate'},
 {'2L': '',
  '3L': 'hsb',
  'english': 'Upper Sorbian',
  'french': 'haut-sorabe'},
 {'2L': 'hu', '3L': 'hun', 'english': 'Hungarian', 'french': 'hongrois'},
 {'2L': '', '3L': 'hup', 'english': 'Hupa', 'french': 'hupa'},
 {'2L': '', '3L': 'iba', 'english': 'Iban', 'french': 'iban'},
 {'2L': 'ig', '3L': 'ibo', 'english': 'Igbo', 'french': 'igbo'},
 {'2L': 'is', '3L': 'ice', 'english': 'Icelandic', 'french': 'islandais'},
 {'2L': 'io', '3L': 'ido', 'english': 'Ido', 'french': 'ido'},
 {'2L': 'ii',
  '3L': 'iii',
  'english': 'Sichuan Yi; Nuosu',
  'french': 'yi de Sichuan'},
 {'2L': '',
  '3L': 'ijo',
  'english': 'Ijo languages',
  'french': 'ijo, langues'},
 {'2L': 'iu', '3L': 'iku', 'english': 'Inuktitut', 'french': 'inuktitut'},
 {'2L': 'ie',
  '3L': 'ile',
  'english': 'Interlingue; Occidental',
  'french': 'interlingue'},
 {'2L': '', '3L': 'ilo', 'english': 'Iloko', 'french': 'ilocano'},
 {'2L': 'ia',
  '3L': 'ina',
  'english': 'Interlingua (International Auxiliary Language Association)',
  'french': 'interlingua (langue auxiliaire internationale)'},
 {'2L': '',
  '3L': 'inc',
  'english': 'Indic languages',
  'french': 'indo-aryennes, langues'},
 {'2L': 'id',
  '3L': 'ind',
  'english': 'Indonesian',
  'french': 'indon\xc3\xa9sien'},
 {'2L': '',
  '3L': 'ine',
  'english': 'Indo-European languages',
  'french': 'indo-europ\xc3\xa9ennes, langues'},
 {'2L': '', '3L': 'inh', 'english': 'Ingush', 'french': 'ingouche'},
 {'2L': 'ik', '3L': 'ipk', 'english': 'Inupiaq', 'french': 'inupiaq'},
 {'2L': '',
  '3L': 'ira',
  'english': 'Iranian languages',
  'french': 'iraniennes, langues'},
 {'2L': '',
  '3L': 'iro',
  'english': 'Iroquoian languages',
  'french': 'iroquoises, langues'},
 {'2L': 'it', '3L': 'ita', 'english': 'Italian', 'french': 'italien'},
 {'2L': 'jv', '3L': 'jav', 'english': 'Javanese', 'french': 'javanais'},
 {'2L': '', '3L': 'jbo', 'english': 'Lojban', 'french': 'lojban'},
 {'2L': 'ja', '3L': 'jpn', 'english': 'Japanese', 'french': 'japonais'},
 {'2L': '',
  '3L': 'jpr',
  'english': 'Judeo-Persian',
  'french': 'jud\xc3\xa9o-persan'},
 {'2L': '',
  '3L': 'jrb',
  'english': 'Judeo-Arabic',
  'french': 'jud\xc3\xa9o-arabe'},
 {'2L': '', '3L': 'kaa', 'english': 'Kara-Kalpak', 'french': 'karakalpak'},
 {'2L': '', '3L': 'kab', 'english': 'Kabyle', 'french': 'kabyle'},
 {'2L': '',
  '3L': 'kac',
  'english': 'Kachin; Jingpho',
  'french': 'kachin; jingpho'},
 {'2L': 'kl',
  '3L': 'kal',
  'english': 'Kalaallisut; Greenlandic',
  'french': 'groenlandais'},
 {'2L': '', '3L': 'kam', 'english': 'Kamba', 'french': 'kamba'},
 {'2L': 'kn', '3L': 'kan', 'english': 'Kannada', 'french': 'kannada'},
 {'2L': '',
  '3L': 'kar',
  'english': 'Karen languages',
  'french': 'karen, langues'},
 {'2L': 'ks', '3L': 'kas', 'english': 'Kashmiri', 'french': 'kashmiri'},
 {'2L': 'kr', '3L': 'kau', 'english': 'Kanuri', 'french': 'kanouri'},
 {'2L': '', '3L': 'kaw', 'english': 'Kawi', 'french': 'kawi'},
 {'2L': 'kk', '3L': 'kaz', 'english': 'Kazakh', 'french': 'kazakh'},
 {'2L': '', '3L': 'kbd', 'english': 'Kabardian', 'french': 'kabardien'},
 {'2L': '', '3L': 'kha', 'english': 'Khasi', 'french': 'khasi'},
 {'2L': '',
  '3L': 'khi',
  'english': 'Khoisan languages',
  'french': 'kho\xc3\xafsan, langues'},
 {'2L': 'km',
  '3L': 'khm',
  'english': 'Central Khmer',
  'french': 'khmer central'},
 {'2L': '',
  '3L': 'kho',
  'english': 'Khotanese; Sakan',
  'french': 'khotanais; sakan'},
 {'2L': 'ki', '3L': 'kik', 'english': 'Kikuyu; Gikuyu', 'french': 'kikuyu'},
 {'2L': 'rw', '3L': 'kin', 'english': 'Kinyarwanda', 'french': 'rwanda'},
 {'2L': 'ky',
  '3L': 'kir',
  'english': 'Kirghiz; Kyrgyz',
  'french': 'kirghiz'},
 {'2L': '', '3L': 'kmb', 'english': 'Kimbundu', 'french': 'kimbundu'},
 {'2L': '', '3L': 'kok', 'english': 'Konkani', 'french': 'konkani'},
 {'2L': 'kv', '3L': 'kom', 'english': 'Komi', 'french': 'kom'},
 {'2L': 'kg', '3L': 'kon', 'english': 'Kongo', 'french': 'kongo'},
 {'2L': 'ko', '3L': 'kor', 'english': 'Korean', 'french': 'cor\xc3\xa9en'},
 {'2L': '', '3L': 'kos', 'english': 'Kosraean', 'french': 'kosrae'},
 {'2L': '', '3L': 'kpe', 'english': 'Kpelle', 'french': 'kpell\xc3\xa9'},
 {'2L': '',
  '3L': 'krc',
  'english': 'Karachay-Balkar',
  'french': 'karatchai balkar'},
 {'2L': '', '3L': 'krl', 'english': 'Karelian', 'french': 'car\xc3\xa9lien'},
 {'2L': '',
  '3L': 'kro',
  'english': 'Kru languages',
  'french': 'krou, langues'},
 {'2L': '', '3L': 'kru', 'english': 'Kurukh', 'french': 'kurukh'},
 {'2L': 'kj',
  '3L': 'kua',
  'english': 'Kuanyama; Kwanyama',
  'french': 'kuanyama; kwanyama'},
 {'2L': '', '3L': 'kum', 'english': 'Kumyk', 'french': 'koumyk'},
 {'2L': 'ku', '3L': 'kur', 'english': 'Kurdish', 'french': 'kurde'},
 {'2L': '', '3L': 'kut', 'english': 'Kutenai', 'french': 'kutenai'},
 {'2L': '',
  '3L': 'lad',
  'english': 'Ladino',
  'french': 'jud\xc3\xa9o-espagnol'},
 {'2L': '', '3L': 'lah', 'english': 'Lahnda', 'french': 'lahnda'},
 {'2L': '', '3L': 'lam', 'english': 'Lamba', 'french': 'lamba'},
 {'2L': 'lo', '3L': 'lao', 'english': 'Lao', 'french': 'lao'},
 {'2L': 'la', '3L': 'lat', 'english': 'Latin', 'french': 'latin'},
 {'2L': 'lv', '3L': 'lav', 'english': 'Latvian', 'french': 'letton'},
 {'2L': '', '3L': 'lez', 'english': 'Lezghian', 'french': 'lezghien'},
 {'2L': 'li',
  '3L': 'lim',
  'english': 'Limburgan; Limburger; Limburgish',
  'french': 'limbourgeois'},
 {'2L': 'ln', '3L': 'lin', 'english': 'Lingala', 'french': 'lingala'},
 {'2L': 'lt', '3L': 'lit', 'english': 'Lithuanian', 'french': 'lituanien'},
 {'2L': '', '3L': 'lol', 'english': 'Mongo', 'french': 'mongo'},
 {'2L': '', '3L': 'loz', 'english': 'Lozi', 'french': 'lozi'},
 {'2L': 'lb',
  '3L': 'ltz',
  'english': 'Luxembourgish; Letzeburgesch',
  'french': 'luxembourgeois'},
 {'2L': '', '3L': 'lua', 'english': 'Luba-Lulua', 'french': 'luba-lulua'},
 {'2L': 'lu',
  '3L': 'lub',
  'english': 'Luba-Katanga',
  'french': 'luba-katanga'},
 {'2L': 'lg', '3L': 'lug', 'english': 'Ganda', 'french': 'ganda'},
 {'2L': '', '3L': 'lui', 'english': 'Luiseno', 'french': 'luiseno'},
 {'2L': '', '3L': 'lun', 'english': 'Lunda', 'french': 'lunda'},
 {'2L': '',
  '3L': 'luo',
  'english': 'Luo (Kenya and Tanzania)',
  'french': 'luo (Kenya et Tanzanie)'},
 {'2L': '', '3L': 'lus', 'english': 'Lushai', 'french': 'lushai'},
 {'2L': 'mk',
  '3L': 'mac',
  'english': 'Macedonian',
  'french': 'mac\xc3\xa9donien'},
 {'2L': '', '3L': 'mad', 'english': 'Madurese', 'french': 'madourais'},
 {'2L': '', '3L': 'mag', 'english': 'Magahi', 'french': 'magahi'},
 {'2L': 'mh', '3L': 'mah', 'english': 'Marshallese', 'french': 'marshall'},
 {'2L': '', '3L': 'mai', 'english': 'Maithili', 'french': 'maithili'},
 {'2L': '', '3L': 'mak', 'english': 'Makasar', 'french': 'makassar'},
 {'2L': 'ml', '3L': 'mal', 'english': 'Malayalam', 'french': 'malayalam'},
 {'2L': '', '3L': 'man', 'english': 'Mandingo', 'french': 'mandingue'},
 {'2L': 'mi', '3L': 'mao', 'english': 'Maori', 'french': 'maori'},
 {'2L': '',
  '3L': 'map',
  'english': 'Austronesian languages',
  'french': 'austron\xc3\xa9siennes, langues'},
 {'2L': 'mr', '3L': 'mar', 'english': 'Marathi', 'french': 'marathe'},
 {'2L': '', '3L': 'mas', 'english': 'Masai', 'french': 'massa\xc3\xaf'},
 {'2L': 'ms', '3L': 'may', 'english': 'Malay', 'french': 'malais'},
 {'2L': '', '3L': 'mdf', 'english': 'Moksha', 'french': 'moksa'},
 {'2L': '', '3L': 'mdr', 'english': 'Mandar', 'french': 'mandar'},
 {'2L': '', '3L': 'men', 'english': 'Mende', 'french': 'mend\xc3\xa9'},
 {'2L': '',
  '3L': 'mga',
  'english': 'Irish, Middle (900-1200)',
  'french': 'irlandais moyen (900-1200)'},
 {'2L': '',
  '3L': 'mic',
  'english': "Mi'kmaq; Micmac",
  'french': "mi'kmaq; micmac"},
 {'2L': '', '3L': 'min', 'english': 'Minangkabau', 'french': 'minangkabau'},
 {'2L': '',
  '3L': 'mis',
  'english': 'Uncoded languages',
  'french': 'langues non cod\xc3\xa9es'},
 {'2L': '',
  '3L': 'mkh',
  'english': 'Mon-Khmer languages',
  'french': 'm\xc3\xb4n-khmer, langues'},
 {'2L': 'mg', '3L': 'mlg', 'english': 'Malagasy', 'french': 'malgache'},
 {'2L': 'mt', '3L': 'mlt', 'english': 'Maltese', 'french': 'maltais'},
 {'2L': '', '3L': 'mnc', 'english': 'Manchu', 'french': 'mandchou'},
 {'2L': '', '3L': 'mni', 'english': 'Manipuri', 'french': 'manipuri'},
 {'2L': '',
  '3L': 'mno',
  'english': 'Manobo languages',
  'french': 'manobo, langues'},
 {'2L': '', '3L': 'moh', 'english': 'Mohawk', 'french': 'mohawk'},
 {'2L': 'mn', '3L': 'mon', 'english': 'Mongolian', 'french': 'mongol'},
 {'2L': '', '3L': 'mos', 'english': 'Mossi', 'french': 'mor\xc3\xa9'},
 {'2L': '',
  '3L': 'mul',
  'english': 'Multiple languages',
  'french': 'multilingue'},
 {'2L': '',
  '3L': 'mun',
  'english': 'Munda languages',
  'french': 'mounda, langues'},
 {'2L': '', '3L': 'mus', 'english': 'Creek', 'french': 'muskogee'},
 {'2L': '', '3L': 'mwl', 'english': 'Mirandese', 'french': 'mirandais'},
 {'2L': '', '3L': 'mwr', 'english': 'Marwari', 'french': 'marvari'},
 {'2L': '',
  '3L': 'myn',
  'english': 'Mayan languages',
  'french': 'maya, langues'},
 {'2L': '', '3L': 'myv', 'english': 'Erzya', 'french': 'erza'},
 {'2L': '',
  '3L': 'nah',
  'english': 'Nahuatl languages',
  'french': 'nahuatl, langues'},
 {'2L': '',
  '3L': 'nai',
  'english': 'North American Indian languages',
  'french': 'nord-am\xc3\xa9rindiennes, langues'},
 {'2L': '', '3L': 'nap', 'english': 'Neapolitan', 'french': 'napolitain'},
 {'2L': 'na', '3L': 'nau', 'english': 'Nauru', 'french': 'nauruan'},
 {'2L': 'nv', '3L': 'nav', 'english': 'Navajo; Navaho', 'french': 'navaho'},
 {'2L': 'nr',
  '3L': 'nbl',
  'english': 'Ndebele, South; South Ndebele',
  'french': 'nd\xc3\xa9b\xc3\xa9l\xc3\xa9 du Sud'},
 {'2L': 'nd',
  '3L': 'nde',
  'english': 'Ndebele, North; North Ndebele',
  'french': 'nd\xc3\xa9b\xc3\xa9l\xc3\xa9 du Nord'},
 {'2L': 'ng', '3L': 'ndo', 'english': 'Ndonga', 'french': 'ndonga'},
 {'2L': '',
  '3L': 'nds',
  'english': 'Low German; Low Saxon; German, Low; Saxon, Low',
  'french': 'bas allemand; bas saxon; allemand, bas; saxon, bas'},
 {'2L': 'ne', '3L': 'nep', 'english': 'Nepali', 'french': 'n\xc3\xa9palais'},
 {'2L': '',
  '3L': 'new',
  'english': 'Nepal Bhasa; Newari',
  'french': 'nepal bhasa; newari'},
 {'2L': '', '3L': 'nia', 'english': 'Nias', 'french': 'nias'},
 {'2L': '',
  '3L': 'nic',
  'english': 'Niger-Kordofanian languages',
  'french': 'nig\xc3\xa9ro-kordofaniennes, langues'},
 {'2L': '', '3L': 'niu', 'english': 'Niuean', 'french': 'niu\xc3\xa9'},
 {'2L': 'nn',
  '3L': 'nno',
  'english': 'Norwegian Nynorsk; Nynorsk, Norwegian',
  'french': 'norv\xc3\xa9gien nynorsk; nynorsk, norv\xc3\xa9gien'},
 {'2L': 'nb',
  '3L': 'nob',
  'english': 'Bokm\xc3\xa5l, Norwegian; Norwegian Bokm\xc3\xa5l',
  'french': 'norv\xc3\xa9gien bokm\xc3\xa5l'},
 {'2L': '',
  '3L': 'nog',
  'english': 'Nogai',
  'french': 'noga\xc3\xaf; nogay'},
 {'2L': '',
  '3L': 'non',
  'english': 'Norse, Old',
  'french': 'norrois, vieux'},
 {'2L': 'no',
  '3L': 'nor',
  'english': 'Norwegian',
  'french': 'norv\xc3\xa9gien'},
 {'2L': '', '3L': 'nqo', 'english': "N'Ko", 'french': "n'ko"},
 {'2L': '',
  '3L': 'nso',
  'english': 'Pedi; Sepedi; Northern Sotho',
  'french': 'pedi; sepedi; sotho du Nord'},
 {'2L': '',
  '3L': 'nub',
  'english': 'Nubian languages',
  'french': 'nubiennes, langues'},
 {'2L': '',
  '3L': 'nwc',
  'english': 'Classical Newari; Old Newari; Classical Nepal Bhasa',
  'french': 'newari classique'},
 {'2L': 'ny',
  '3L': 'nya',
  'english': 'Chichewa; Chewa; Nyanja',
  'french': 'chichewa; chewa; nyanja'},
 {'2L': '', '3L': 'nym', 'english': 'Nyamwezi', 'french': 'nyamwezi'},
 {'2L': '', '3L': 'nyn', 'english': 'Nyankole', 'french': 'nyankol\xc3\xa9'},
 {'2L': '', '3L': 'nyo', 'english': 'Nyoro', 'french': 'nyoro'},
 {'2L': '', '3L': 'nzi', 'english': 'Nzima', 'french': 'nzema'},
 {'2L': 'oc',
  '3L': 'oci',
  'english': 'Occitan (post 1500); Proven\xc3\xa7al',
  'french': 'occitan (apr\xc3\xa8s 1500); proven\xc3\xa7al'},
 {'2L': 'oj', '3L': 'oji', 'english': 'Ojibwa', 'french': 'ojibwa'},
 {'2L': 'or', '3L': 'ori', 'english': 'Oriya', 'french': 'oriya'},
 {'2L': 'om', '3L': 'orm', 'english': 'Oromo', 'french': 'galla'},
 {'2L': '', '3L': 'osa', 'english': 'Osage', 'french': 'osage'},
 {'2L': 'os',
  '3L': 'oss',
  'english': 'Ossetian; Ossetic',
  'french': 'oss\xc3\xa8te'},
 {'2L': '',
  '3L': 'ota',
  'english': 'Turkish, Ottoman (1500-1928)',
  'french': 'turc ottoman (1500-1928)'},
 {'2L': '',
  '3L': 'oto',
  'english': 'Otomian languages',
  'french': 'otomi, langues'},
 {'2L': '',
  '3L': 'paa',
  'english': 'Papuan languages',
  'french': 'papoues, langues'},
 {'2L': '', '3L': 'pag', 'english': 'Pangasinan', 'french': 'pangasinan'},
 {'2L': '', '3L': 'pal', 'english': 'Pahlavi', 'french': 'pahlavi'},
 {'2L': '',
  '3L': 'pam',
  'english': 'Pampanga; Kapampangan',
  'french': 'pampangan'},
 {'2L': 'pa',
  '3L': 'pan',
  'english': 'Panjabi; Punjabi',
  'french': 'pendjabi'},
 {'2L': '', '3L': 'pap', 'english': 'Papiamento', 'french': 'papiamento'},
 {'2L': '', '3L': 'pau', 'english': 'Palauan', 'french': 'palau'},
 {'2L': '',
  '3L': 'peo',
  'english': 'Persian, Old (ca.600-400 B.C.)',
  'french': 'perse, vieux (ca. 600-400 av. J.-C.)'},
 {'2L': 'fa', '3L': 'per', 'english': 'Persian', 'french': 'persan'},
 {'2L': '',
  '3L': 'phi',
  'english': 'Philippine languages',
  'french': 'philippines, langues'},
 {'2L': '',
  '3L': 'phn',
  'english': 'Phoenician',
  'french': 'ph\xc3\xa9nicien'},
 {'2L': 'pi', '3L': 'pli', 'english': 'Pali', 'french': 'pali'},
 {'2L': 'pl', '3L': 'pol', 'english': 'Polish', 'french': 'polonais'},
 {'2L': '', '3L': 'pon', 'english': 'Pohnpeian', 'french': 'pohnpei'},
 {'2L': 'pt', '3L': 'por', 'english': 'Portuguese', 'french': 'portugais'},
 {'2L': '',
  '3L': 'pra',
  'english': 'Prakrit languages',
  'french': 'pr\xc3\xa2krit, langues'},
 {'2L': '',
  '3L': 'pro',
  'english': 'Proven\xc3\xa7al, Old (to 1500)',
  'french': "proven\xc3\xa7al ancien (jusqu'\xc3\xa0 1500)"},
 {'2L': 'ps', '3L': 'pus', 'english': 'Pushto; Pashto', 'french': 'pachto'},
 {'2L': '',
  '3L': 'qaa-qtz',
  'english': 'Reserved for local use',
  'french': "r\xc3\xa9serv\xc3\xa9e \xc3\xa0 l'usage local"},
 {'2L': 'qu', '3L': 'que', 'english': 'Quechua', 'french': 'quechua'},
 {'2L': '', '3L': 'raj', 'english': 'Rajasthani', 'french': 'rajasthani'},
 {'2L': '', '3L': 'rap', 'english': 'Rapanui', 'french': 'rapanui'},
 {'2L': '',
  '3L': 'rar',
  'english': 'Rarotongan; Cook Islands Maori',
  'french': 'rarotonga; maori des \xc3\xaeles Cook'},
 {'2L': '',
  '3L': 'roa',
  'english': 'Romance languages',
  'french': 'romanes, langues'},
 {'2L': 'rm', '3L': 'roh', 'english': 'Romansh', 'french': 'romanche'},
 {'2L': '', '3L': 'rom', 'english': 'Romany', 'french': 'tsigane'},
 {'2L': 'ro',
  '3L': 'rum',
  'english': 'Romanian; Moldavian; Moldovan',
  'french': 'roumain; moldave'},
 {'2L': 'rn', '3L': 'run', 'english': 'Rundi', 'french': 'rundi'},
 {'2L': '',
  '3L': 'rup',
  'english': 'Aromanian; Arumanian; Macedo-Romanian',
  'french': 'aroumain; mac\xc3\xa9do-roumain'},
 {'2L': 'ru', '3L': 'rus', 'english': 'Russian', 'french': 'russe'},
 {'2L': '', '3L': 'sad', 'english': 'Sandawe', 'french': 'sandawe'},
 {'2L': 'sg', '3L': 'sag', 'english': 'Sango', 'french': 'sango'},
 {'2L': '', '3L': 'sah', 'english': 'Yakut', 'french': 'iakoute'},
 {'2L': '',
  '3L': 'sai',
  'english': 'South American Indian (Other)',
  'french': "indiennes d'Am\xc3\xa9rique du Sud, autres langues"},
 {'2L': '',
  '3L': 'sal',
  'english': 'Salishan languages',
  'french': 'salishennes, langues'},
 {'2L': '',
  '3L': 'sam',
  'english': 'Samaritan Aramaic',
  'french': 'samaritain'},
 {'2L': 'sa', '3L': 'san', 'english': 'Sanskrit', 'french': 'sanskrit'},
 {'2L': '', '3L': 'sas', 'english': 'Sasak', 'french': 'sasak'},
 {'2L': '', '3L': 'sat', 'english': 'Santali', 'french': 'santal'},
 {'2L': '', '3L': 'scn', 'english': 'Sicilian', 'french': 'sicilien'},
 {'2L': '', '3L': 'sco', 'english': 'Scots', 'french': '\xc3\xa9cossais'},
 {'2L': '', '3L': 'sel', 'english': 'Selkup', 'french': 'selkoupe'},
 {'2L': '',
  '3L': 'sem',
  'english': 'Semitic languages',
  'french': 's\xc3\xa9mitiques, langues'},
 {'2L': '',
  '3L': 'sga',
  'english': 'Irish, Old (to 900)',
  'french': "irlandais ancien (jusqu'\xc3\xa0 900)"},
 {'2L': '',
  '3L': 'sgn',
  'english': 'Sign Languages',
  'french': 'langues des signes'},
 {'2L': '', '3L': 'shn', 'english': 'Shan', 'french': 'chan'},
 {'2L': '', '3L': 'sid', 'english': 'Sidamo', 'french': 'sidamo'},
 {'2L': 'si',
  '3L': 'sin',
  'english': 'Sinhala; Sinhalese',
  'french': 'singhalais'},
 {'2L': '',
  '3L': 'sio',
  'english': 'Siouan languages',
  'french': 'sioux, langues'},
 {'2L': '',
  '3L': 'sit',
  'english': 'Sino-Tibetan languages',
  'french': 'sino-tib\xc3\xa9taines, langues'},
 {'2L': '',
  '3L': 'sla',
  'english': 'Slavic languages',
  'french': 'slaves, langues'},
 {'2L': 'sk', '3L': 'slo', 'english': 'Slovak', 'french': 'slovaque'},
 {'2L': 'sl',
  '3L': 'slv',
  'english': 'Slovenian',
  'french': 'slov\xc3\xa8ne'},
 {'2L': '',
  '3L': 'sma',
  'english': 'Southern Sami',
  'french': 'sami du Sud'},
 {'2L': 'se',
  '3L': 'sme',
  'english': 'Northern Sami',
  'french': 'sami du Nord'},
 {'2L': '',
  '3L': 'smi',
  'english': 'Sami languages',
  'french': 'sames, langues'},
 {'2L': '', '3L': 'smj', 'english': 'Lule Sami', 'french': 'sami de Lule'},
 {'2L': '', '3L': 'smn', 'english': 'Inari Sami', 'french': "sami d'Inari"},
 {'2L': 'sm', '3L': 'smo', 'english': 'Samoan', 'french': 'samoan'},
 {'2L': '', '3L': 'sms', 'english': 'Skolt Sami', 'french': 'sami skolt'},
 {'2L': 'sn', '3L': 'sna', 'english': 'Shona', 'french': 'shona'},
 {'2L': 'sd', '3L': 'snd', 'english': 'Sindhi', 'french': 'sindhi'},
 {'2L': '', '3L': 'snk', 'english': 'Soninke', 'french': 'sonink\xc3\xa9'},
 {'2L': '', '3L': 'sog', 'english': 'Sogdian', 'french': 'sogdien'},
 {'2L': 'so', '3L': 'som', 'english': 'Somali', 'french': 'somali'},
 {'2L': '',
  '3L': 'son',
  'english': 'Songhai languages',
  'french': 'songhai, langues'},
 {'2L': 'st',
  '3L': 'sot',
  'english': 'Sotho, Southern',
  'french': 'sotho du Sud'},
 {'2L': 'es',
  '3L': 'spa',
  'english': 'Spanish; Castilian',
  'french': 'espagnol; castillan'},
 {'2L': 'sc', '3L': 'srd', 'english': 'Sardinian', 'french': 'sarde'},
 {'2L': '',
  '3L': 'srn',
  'english': 'Sranan Tongo',
  'french': 'sranan tongo'},
 {'2L': 'sr', '3L': 'srp', 'english': 'Serbian', 'french': 'serbe'},
 {'2L': '',
  '3L': 'srr',
  'english': 'Serer',
  'french': 's\xc3\xa9r\xc3\xa8re'},
 {'2L': '',
  '3L': 'ssa',
  'english': 'Nilo-Saharan languages',
  'french': 'nilo-sahariennes, langues'},
 {'2L': 'ss', '3L': 'ssw', 'english': 'Swati', 'french': 'swati'},
 {'2L': '', '3L': 'suk', 'english': 'Sukuma', 'french': 'sukuma'},
 {'2L': 'su', '3L': 'sun', 'english': 'Sundanese', 'french': 'soundanais'},
 {'2L': '', '3L': 'sus', 'english': 'Susu', 'french': 'soussou'},
 {'2L': '', '3L': 'sux', 'english': 'Sumerian', 'french': 'sum\xc3\xa9rien'},
 {'2L': 'sw', '3L': 'swa', 'english': 'Swahili', 'french': 'swahili'},
 {'2L': 'sv', '3L': 'swe', 'english': 'Swedish', 'french': 'su\xc3\xa9dois'},
 {'2L': '',
  '3L': 'syc',
  'english': 'Classical Syriac',
  'french': 'syriaque classique'},
 {'2L': '', '3L': 'syr', 'english': 'Syriac', 'french': 'syriaque'},
 {'2L': 'ty', '3L': 'tah', 'english': 'Tahitian', 'french': 'tahitien'},
 {'2L': '',
  '3L': 'tai',
  'english': 'Tai languages',
  'french': 'tai, langues'},
 {'2L': 'ta', '3L': 'tam', 'english': 'Tamil', 'french': 'tamoul'},
 {'2L': 'tt', '3L': 'tat', 'english': 'Tatar', 'french': 'tatar'},
 {'2L': 'te', '3L': 'tel', 'english': 'Telugu', 'french': 't\xc3\xa9lougou'},
 {'2L': '', '3L': 'tem', 'english': 'Timne', 'french': 'temne'},
 {'2L': '', '3L': 'ter', 'english': 'Tereno', 'french': 'tereno'},
 {'2L': '', '3L': 'tet', 'english': 'Tetum', 'french': 'tetum'},
 {'2L': 'tg', '3L': 'tgk', 'english': 'Tajik', 'french': 'tadjik'},
 {'2L': 'tl', '3L': 'tgl', 'english': 'Tagalog', 'french': 'tagalog'},
 {'2L': 'th', '3L': 'tha', 'english': 'Thai', 'french': 'tha\xc3\xaf'},
 {'2L': 'bo',
  '3L': 'tib',
  'english': 'Tibetan',
  'french': 'tib\xc3\xa9tain'},
 {'2L': '', '3L': 'tig', 'english': 'Tigre', 'french': 'tigr\xc3\xa9'},
 {'2L': 'ti', '3L': 'tir', 'english': 'Tigrinya', 'french': 'tigrigna'},
 {'2L': '', '3L': 'tiv', 'english': 'Tiv', 'french': 'tiv'},
 {'2L': '', '3L': 'tkl', 'english': 'Tokelau', 'french': 'tokelau'},
 {'2L': '',
  '3L': 'tlh',
  'english': 'Klingon; tlhIngan-Hol',
  'french': 'klingon'},
 {'2L': '', '3L': 'tli', 'english': 'Tlingit', 'french': 'tlingit'},
 {'2L': '', '3L': 'tmh', 'english': 'Tamashek', 'french': 'tamacheq'},
 {'2L': '',
  '3L': 'tog',
  'english': 'Tonga (Nyasa)',
  'french': 'tonga (Nyasa)'},
 {'2L': 'to',
  '3L': 'ton',
  'english': 'Tonga (Tonga Islands)',
  'french': 'tongan (\xc3\x8eles Tonga)'},
 {'2L': '', '3L': 'tpi', 'english': 'Tok Pisin', 'french': 'tok pisin'},
 {'2L': '', '3L': 'tsi', 'english': 'Tsimshian', 'french': 'tsimshian'},
 {'2L': 'tn', '3L': 'tsn', 'english': 'Tswana', 'french': 'tswana'},
 {'2L': 'ts', '3L': 'tso', 'english': 'Tsonga', 'french': 'tsonga'},
 {'2L': 'tk',
  '3L': 'tuk',
  'english': 'Turkmen',
  'french': 'turkm\xc3\xa8ne'},
 {'2L': '', '3L': 'tum', 'english': 'Tumbuka', 'french': 'tumbuka'},
 {'2L': '',
  '3L': 'tup',
  'english': 'Tupi languages',
  'french': 'tupi, langues'},
 {'2L': 'tr', '3L': 'tur', 'english': 'Turkish', 'french': 'turc'},
 {'2L': '',
  '3L': 'tut',
  'english': 'Altaic languages',
  'french': 'alta\xc3\xafques, langues'},
 {'2L': '', '3L': 'tvl', 'english': 'Tuvalu', 'french': 'tuvalu'},
 {'2L': 'tw', '3L': 'twi', 'english': 'Twi', 'french': 'twi'},
 {'2L': '', '3L': 'tyv', 'english': 'Tuvinian', 'french': 'touva'},
 {'2L': '', '3L': 'udm', 'english': 'Udmurt', 'french': 'oudmourte'},
 {'2L': '', '3L': 'uga', 'english': 'Ugaritic', 'french': 'ougaritique'},
 {'2L': 'ug',
  '3L': 'uig',
  'english': 'Uighur; Uyghur',
  'french': 'ou\xc3\xafgour'},
 {'2L': 'uk', '3L': 'ukr', 'english': 'Ukrainian', 'french': 'ukrainien'},
 {'2L': '', '3L': 'umb', 'english': 'Umbundu', 'french': 'umbundu'},
 {'2L': '',
  '3L': 'und',
  'english': 'Undetermined',
  'french': 'ind\xc3\xa9termin\xc3\xa9e'},
 {'2L': 'ur', '3L': 'urd', 'english': 'Urdu', 'french': 'ourdou'},
 {'2L': 'uz', '3L': 'uzb', 'english': 'Uzbek', 'french': 'ouszbek'},
 {'2L': '', '3L': 'vai', 'english': 'Vai', 'french': 'va\xc3\xaf'},
 {'2L': 've', '3L': 'ven', 'english': 'Venda', 'french': 'venda'},
 {'2L': 'vi', '3L': 'vie', 'english': 'Vietnamese', 'french': 'vietnamien'},
 {'2L': 'vo',
  '3L': 'vol',
  'english': 'Volap\xc3\xbck',
  'french': 'volap\xc3\xbck'},
 {'2L': '', '3L': 'vot', 'english': 'Votic', 'french': 'vote'},
 {'2L': '',
  '3L': 'wak',
  'english': 'Wakashan languages',
  'french': 'wakashanes, langues'},
 {'2L': '', '3L': 'wal', 'english': 'Walamo', 'french': 'walamo'},
 {'2L': '', '3L': 'war', 'english': 'Waray', 'french': 'waray'},
 {'2L': '', '3L': 'was', 'english': 'Washo', 'french': 'washo'},
 {'2L': 'cy', '3L': 'wel', 'english': 'Welsh', 'french': 'gallois'},
 {'2L': '',
  '3L': 'wen',
  'english': 'Sorbian languages',
  'french': 'sorabes, langues'},
 {'2L': 'wa', '3L': 'wln', 'english': 'Walloon', 'french': 'wallon'},
 {'2L': 'wo', '3L': 'wol', 'english': 'Wolof', 'french': 'wolof'},
 {'2L': '',
  '3L': 'xal',
  'english': 'Kalmyk; Oirat',
  'french': 'kalmouk; o\xc3\xafrat'},
 {'2L': 'xh', '3L': 'xho', 'english': 'Xhosa', 'french': 'xhosa'},
 {'2L': '', '3L': 'yao', 'english': 'Yao', 'french': 'yao'},
 {'2L': '', '3L': 'yap', 'english': 'Yapese', 'french': 'yapois'},
 {'2L': 'yi', '3L': 'yid', 'english': 'Yiddish', 'french': 'yiddish'},
 {'2L': 'yo', '3L': 'yor', 'english': 'Yoruba', 'french': 'yoruba'},
 {'2L': '',
  '3L': 'ypk',
  'english': 'Yupik languages',
  'french': 'yupik, langues'},
 {'2L': '', '3L': 'zap', 'english': 'Zapotec', 'french': 'zapot\xc3\xa8que'},
 {'2L': '',
  '3L': 'zbl',
  'english': 'Blissymbols; Blissymbolics; Bliss',
  'french': 'symboles Bliss; Bliss'},
 {'2L': '', '3L': 'zen', 'english': 'Zenaga', 'french': 'zenaga'},
 {'2L': 'za',
  '3L': 'zha',
  'english': 'Zhuang; Chuang',
  'french': 'zhuang; chuang'},
 {'2L': '',
  '3L': 'znd',
  'english': 'Zande languages',
  'french': 'zand\xc3\xa9, langues'},
 {'2L': 'zu', '3L': 'zul', 'english': 'Zulu', 'french': 'zoulou'},
 {'2L': '', '3L': 'zun', 'english': 'Zuni', 'french': 'zuni'},
 {'2L': '',
  '3L': 'zxx',
  'english': 'No linguistic content; Not applicable',
  'french': 'pas de contenu linguistique; non applicable'},
 {'2L': '',
  '3L': 'zza',
  'english': 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki',
  'french': 'zaza; dimili; dimli; kirdki; kirmanjki; zazaki'}]
